routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\EmployeeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Role And Permissions
Route::group(['middleware' => ['auth']], function() {

Route::get('users', [App\Http\Controllers\UserController::class, 'index'])->name('users.index');
Route::get('users/create/', [App\Http\Controllers\UserController::class, 'create'])->name('users.create');
Route::post('users/store/', [App\Http\Controllers\UserController::class, 'store'])->name('users.store');
Route::get('users/show/{id}', [App\Http\Controllers\UserController::class, 'show'])->name('users.show');
Route::get('users/edit/{id}', [App\Http\Controllers\UserController::class, 'edit'])->name('users.edit');
Route::patch('users/update/{id}', [App\Http\Controllers\UserController::class, 'update'])->name('users.update');
Route::delete('users/destroy/{id}', [App\Http\Controllers\UserController::class, 'destroy'])->name('users.destroy');

Route::get('users/profile', [App\Http\Controllers\ProfileController::class, 'profile'])->name('users.profile');
Route::patch('users/profileUpdate/{id}', [App\Http\Controllers\ProfileController::class, 'profileUpdate'])->name('users.profileUpdate');

Route::get('roles',[App\Http\Controllers\RoleController::class, 'index'])->name('roles.index');
Route::get('roles/create',[App\Http\Controllers\RoleController::class, 'create'])->name('roles.create');
Route::post('roles/store',[App\Http\Controllers\RoleController::class, 'store'])->name('roles.store');
Route::get('roles/show/{id}', [App\Http\Controllers\RoleController::class, 'show'])->name('roles.show');
Route::get('roles/edit/{id}', [App\Http\Controllers\RoleController::class, 'edit'])->name('roles.edit');
Route::patch('roles/update/{id}', [App\Http\Controllers\RoleController::class, 'update'])->name('roles.update');
Route::delete('roles/destroy/{id}', [App\Http\Controllers\RoleController::class, 'destroy'])->name('roles.destroy');

//Employees
Route::resource('employees', App\Http\Controllers\EmployeeController::class);
Route::get('department/{depId}/positions', [App\Http\Controllers\DepartmentController::class, 'positions'])->name('department.positions');

});

//Mission
Route::group(['middleware' => ['auth']], function() {
Route::resource('mission',App\Http\Controllers\MissionController::class);
Route::get('mission/reback/{id}',[App\Http\Controllers\MissionController::class,'rebackDestroy'])->name('mission_back');

Route::get('province/ods',[App\Http\Controllers\MissionController::class,'getOdsByProId'])->name('province.ods');
Route::get('province/facs',[App\Http\Controllers\MissionController::class,'getFacByProId'])->name('province.facs');
Route::get('position/id/',[App\Http\Controllers\MissionController::class,'getPositionID'])->name('position.id');

});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Position;
use App\Models\EmployeeMission;

class Employee extends Model
{
    private $name;
    protected $fillable=['fullname','sex','position_id','notes'];

    public function position()
    {
        return $this->belongsTo(Position::class);
    }

    public function getNameAttribute(){
        return $this->title . ' ' . $this->fullname . ' ( ' . $this->position->name . ' ' . $this->position->department->name . ' )';
    }

}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Position;
use App\Models\Employee;
use App\Models\Department;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;
use Hash;
class EmployeeController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:employee-list|employee-create|employee-edit|employees-delete', ['only' => ['index','store']]);
        $this->middleware('permission:employee-create', ['only' => ['create','store']]);
        $this->middleware('permission:employee-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:employee-delete', ['only' => ['destroy']]);

    }
    public function index()
    {
        $employees = Employee::all();
        return view('employees.index', compact('employees'));
    }
    public function create()
    {
        $employees = Employee::get();
        $departments = Department::all();
        return view('employees.create',compact('employees','departments'));
    }
    public function store(Request $request){
        // dd($request);
        $this->validate($request, [
            'fullname' => 'required',
            'sex' => 'required',
            'position_id' => 'required',
            'notes' => '',
        ]);
        Employee::create($request->all());
        return redirect()->route('employees.index')
                         ->with('success', __('employee.employee').__('message.success_saved'));
    }
    public function edit($id)
    {
        $employee = Employee::find($id);
        $departments = Department::all();
        $positions = $employee->position->department->positions;
        return view('employees.edit',compact('employee','departments','positions'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'fullname' => 'required',
            'sex' => 'required',
            'position_id' => 'required',
            'notes' => '',
        ]);
        $employee = Employee::find($id);
        $employee ->update($request->all());
        return redirect()->route('employees.index')
            ->with('success', __('employee.employee').__('message.success_updated'));

    }
    public function destroy($id)
    {
        DB::table("employees")->where('id',$id)->delete();
        return redirect()->route('employees.index')
                        ->with('success',__('employee.employee').__('message.success_deleted'));
    }
}

resources/views/employees/create.blade.php
<x-layout>
    <x-forms.base route="{{route('employees.store')}}" backTo=" {{ route('employees.index') }}">
        <x-slot name="title">
                <h4>{{ __('employee.create') }}</h4>
        </x-slot>
        <div class="employee">
            <div class="row">
                <div class="col-12">
                    <x-forms.input
                        label="{{ __('employee.name') }}"
                        name="fullname"
                        placeholder="{{__('employee.name') }}">
                    </x-forms.input>
                </div>
                <div class="col-12">
                    <x-forms.radio name="sex"
                                    label="{{ __('employee.sex') }}"
                                    :ids="array('ប្រុស'=>'male_id', 'ស្រី'=>'female_id')"
                                    :options="array('ប្រុស'=>'ប្រុស','ស្រី'=>'ស្រី')"></x-forms.radio>
                </div>
                <div class="col-12">
                    <x-forms.select
                        label="{{ __('employee.department') }}"
                        name="department"
                        id="department"
                        start="0"
                        :collection="$departments"
                        placeholder="{{ __('employee.department') }}">
                    </x-forms.select>
                </div>
                <div class="col-12">
                    <x-forms.select
                        label="{{ __('employee.position') }}"
                        name="position_id"
                        id="data-positions"
                        placeholder="{{ __('employee.position') }}">
                    </x-forms.select>
                </div>

                <div class="col-12">
                    <x-forms.textarea
                        label="{{ __('employee.note') }}"
                        name="notes">
                    </x-forms.textarea>
                </div>
            </div>
        </div>
        {{-- @dump($errors->all()) --}}
    </x-forms.base>

    <x-slot name="header">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
    </x-slot>
    <x-slot name="endbody">
        @include('employees.empscript.script')
    </x-slot>
</x-layout>

resources/views/employees/edit.blade.php
<x-layout>
    <x-forms.base route="{{route('employees.update', $employee->id)}}" method="patch" backTo=" {{ route('roles.index') }}">
        <x-slot name="title">
             <h4>{{ __('employee.edit') }} {{ $employee->fullname }}</h4>
        </x-slot>
        <div class="employee">
            <div class="row">
                <div class="col-12">
                    <x-forms.input
                        label="{{ __('employee.name') }}"
                        name="fullname"
                        :value="$employee->fullname"
                        placeholder="{{__('employee.name') }}">
                    </x-forms.input>
                </div>
                <div class="col-12">
                    <x-forms.radio name="sex"
                                   label="{{ __('employee.sex') }}"
                                   selected="{{ $employee->sex }}"
                                   :ids="array('ប្រុស'=>'male_id', 'ស្រី'=>'female_id')"
                                   :options="array('ប្រុស'=>'ប្រុស','ស្រី'=>'ស្រី')"></x-forms.radio>
                </div>

                {{-- @dump($employee->position->department->id) --}}
                <div class="col-12">
                    <x-forms.select
                        label="{{ __('employee.department') }}"
                        name="department"
                        id="department"
                        start="0"
                        :collection="$departments"
                        :selected="$employee->position->department->id"
                        placeholder="{{ __('employee.department') }}">
                    </x-forms.select>
                </div>
                <div class="col-12">
                    <x-forms.select
                        label="{{ __('employee.position') }}"
                        name="position_id"
                        id="position"
                        :collection="$positions"
                        :selected="$employee->position->id"
                        placeholder="{{ __('employee.position') }}">
                    </x-forms.select>
                </div>
                <div class="col-12">
                    <x-forms.textarea
                        label="{{ __('employee.note') }}"
                        name="notes"
                        :value="$employee->notes">
                    </x-forms.textarea>
                </div>
            </div>
        </div>
    </x-forms.base>

    <x-slot name="header">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous">
        </script>
    </x-slot>
    <x-slot name="endbody">
        @include('employees.empscript.script')
    </x-slot>
</x-layout>

resources/views/employees/index.blade.php
<x-layout>
    <x-layouts.card>
        <x-slot name="title">
            <div class="float-left">
                <h4 style="padding-top: 6px;">{{__('employee.employee')}}</h4>
            </div>
            <div class="float-right">
                @can('employee-create')
                   <x-forms.button color="success" href="{{route('employees.create')}}" style="font-size: 16px">{{__('employee.create')}}</x-forms.button>
                @endcan
            </div>
        </x-slot>
        <div class="col-12" style="margin-top:20px">
            <x-tables.base id="employee">
                <x-slot name="header">
                    <x-tables.header>{{__('employee.no')}}</x-tables.header>
                    <x-tables.header>{{__('employee.name')}}</x-tables.header>
                    <x-tables.header>{{__('employee.sex')}}</x-tables.header>
                    <x-tables.header>{{__('employee.position')}}</x-tables.header>
                    <x-tables.header>{{__('employee.department')}}</x-tables.header>
                    <x-tables.header>{{__('employee.action')}}</x-tables.header>
                </x-slot>
                @foreach ($employees as $index => $employee)
                    <tr>
                        <td>{{ $index+1 }}</td>
                        <td>{{$employee->fullname}}</td>
                        <td>{{$employee->sex}}</td>
                        <td>{{$employee->position->name}}</td>
                        <td>{{$employee->position->department->name}}</td>
                        <td class="edit">
                            <x-tables.action
                                id="{{ $index }}"
                                editPermission="employee-edit"
                                deletePermission="employee-delete"
                                edit="{{route('employees.edit', $employee->id) }}"
                                destroy="{{route('employees.destroy', $employee->id) }}">
                            </x-tables.action>
                        </td>
                    </tr>
                @endforeach
            </x-tables.base>
        </div>
    </x-layouts.card>
    <x-slot name="endbody">
        <script>
            $(document).ready( function (){
                $('#employee').DataTable(
                    {
                        "language": {
                            url : "https://cdn.datatables.net/plug-ins/1.10.22/i18n/Khmer.json"

                        },
                        "iDisplayLength": 25
                    }
                );
            });
        </script>
    </x-slot>

     <x-slot name="header">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
        <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js" defer></script>
        <link rel="stylesheet" href="//cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css" />
    </x-slot>
</x-layout>