routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\EmployeeController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
//Role And Permissions
Route::group(['middleware' => ['auth']], function() {

Route::get('users', [App\Http\Controllers\UserController::class, 'index'])->name('users.index');
Route::get('users/create/', [App\Http\Controllers\UserController::class, 'create'])->name('users.create');
Route::post('users/store/', [App\Http\Controllers\UserController::class, 'store'])->name('users.store');
Route::get('users/show/{id}', [App\Http\Controllers\UserController::class, 'show'])->name('users.show');
Route::get('users/edit/{id}', [App\Http\Controllers\UserController::class, 'edit'])->name('users.edit');
Route::patch('users/update/{id}', [App\Http\Controllers\UserController::class, 'update'])->name('users.update');
Route::delete('users/destroy/{id}', [App\Http\Controllers\UserController::class, 'destroy'])->name('users.destroy');

Route::get('users/profile', [App\Http\Controllers\ProfileController::class, 'profile'])->name('users.profile');
Route::patch('users/profileUpdate/{id}', [App\Http\Controllers\ProfileController::class, 'profileUpdate'])->name('users.profileUpdate');

Route::get('roles',[App\Http\Controllers\RoleController::class, 'index'])->name('roles.index');
Route::get('roles/create',[App\Http\Controllers\RoleController::class, 'create'])->name('roles.create');
Route::post('roles/store',[App\Http\Controllers\RoleController::class, 'store'])->name('roles.store');
Route::get('roles/show/{id}', [App\Http\Controllers\RoleController::class, 'show'])->name('roles.show');
Route::get('roles/edit/{id}', [App\Http\Controllers\RoleController::class, 'edit'])->name('roles.edit');
Route::patch('roles/update/{id}', [App\Http\Controllers\RoleController::class, 'update'])->name('roles.update');
Route::delete('roles/destroy/{id}', [App\Http\Controllers\RoleController::class, 'destroy'])->name('roles.destroy');

//Employees
Route::resource('employees', App\Http\Controllers\EmployeeController::class);
Route::get('department/{depId}/positions', [App\Http\Controllers\DepartmentController::class, 'positions'])->name('department.positions');

});

//Mission
Route::group(['middleware' => ['auth']], function() {
Route::resource('mission',App\Http\Controllers\MissionController::class);
Route::get('mission/reback/{id}',[App\Http\Controllers\MissionController::class,'rebackDestroy'])->name('mission_back');

Route::get('province/ods',[App\Http\Controllers\MissionController::class,'getOdsByProId'])->name('province.ods');
Route::get('province/facs',[App\Http\Controllers\MissionController::class,'getFacByProId'])->name('province.facs');
Route::get('position/id/',[App\Http\Controllers\MissionController::class,'getPositionID'])->name('position.id');

});

app/Models/Mission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use KhmerDateTime\KhmerDateTime;
use Illuminate\Database\Eloquent\Model;
use App\Models\Province;
use App\Models\OperationalDistrict;
use App\Models\HealthFacility;
use App\Models\Objective;
use App\Models\Transportation;
use App\Models\EmployeeMission;
use App\Models\Destination;
use App\Models\Missionable;
use Illuminate\Support\Facades\Auth;

class Mission extends BaseModel
{
    use HasFactory;

    protected $dates = ['leave_date', 'return_date'];

    protected $fillable = ['code', 'reference_document','notes', 'leave_date', 'return_date',
        'objective_id', 'transportation_id', 'budget_id', 'status_id', 'updated_by'];


    public function provinces()
    {
        return $this->morphedByMany(Province::class, 'missionable');
    }

    public function operationalDistricts()
    {
        return $this->morphedByMany(OperationalDistrict::class, 'missionable');
    }

    public function healthFacilities()
    {
        return $this->morphedByMany(HealthFacility::class, 'missionable');
    }

    public function objective()
    {
        return $this->belongsTo(Objective::class);
    }

    public function transportation()
    {
        return $this->belongsTo(Transportation::class);
    }

    public function members()
    {
        return $this->belongsToMany(Employee::class)
            ->withPivot('mission_role_id')
            ->using(MissionRolePivot::class);
    }

    public function missioned(){
        return $this->hasMany(Missionable::class);
    }

    public function getDestinationsAttribute(){
        return array_merge(
            $this->provinces->pluck('name')->toArray(),
            $this->operationalDistricts->pluck('fullname')->toArray(),
            $this->healthFacilities->pluck('completename')->toArray());
    }

    public function getKhLeaveDateAttribute(){
        $dateTime = KhmerDateTime::parse($this->leave_date);
        return $dateTime->format("LL");
    }

    public function getKhReturnDateAttribute(){
        $dateTime = KhmerDateTime::parse($this->return_date);
        return $dateTime->format("LL");
    }

}

app/Http/Controllers/MissionController.php
<?php

namespace App\Http\Controllers;
use App\Http\Requests\MissionRequest;
use Auth;
use Illuminate\Http\Request;
use App\Models\Province;
use App\Models\Mission;
use App\Models\OperationalDistrict;
use App\Models\HealthFacility;
use App\Models\Employee;
use App\Models\Position;
use App\Models\Department;
use App\Models\ContractType;
use App\Models\MissionRole;
use App\Models\Budget;
use App\Models\Objective;
use App\Models\Transportation;
use App\Models\EmployeeMission;
use DB;
use App\Http\Requests\createrequest\MissionCreateRequest;
use Illuminate\View\View;



class MissionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    function __construct()
    {
         $this->middleware('permission:mission-detail',['only' => ['show']]);
         $this->middleware('permission:mission-create', ['only' => ['create','store']]);
         $this->middleware('permission:mission-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:mission-delete', ['only' => ['destroy']]);
    }

    public function index()
    {
            $missions = Mission::with('members','provinces','operationalDistricts.province','healthFacilities.operationalDistrict.province','healthFacilities.healthFacilityType')
                ->where("status_id", "=", 1)
                ->orderBy('id', 'DESC')
                ->get();

            //dd($missions);
            return view('missions.index',['missions'=>$missions]);


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {
        $employees = Employee::with(['position'],['department'])->get();
        $objectives = Objective::select('name','id')->get();
        $budgets = Budget::select('name','id')->get();
        $roles = MissionRole::select('name','id')->get();
        $transportations = Transportation::select('name','id','plate_number')->get();
        $provinces = Province::get();

        return view('missions.create',[
            'provinces' => $provinces,
            'employees'=>$employees,
            'roles' => $roles,
            'budgets'=>$budgets,
            'objectives'=>$objectives,
            'transportations'=>$transportations
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function store(MissionRequest $request)
    {
        $transportation = $request->all();
        foreach($request->health_facilities as $index => $hf) {
            if ($request->health_facilities[$index] > 0){
                unset($transportation['operational_districts'][$index]);
                unset($transportation['provinces'][$index]);
            }
        }
        foreach($transportation['operational_districts'] as $index => $od) {
            if ($transportation['operational_districts'][$index] > 0){
                unset($transportation['provinces'][$index]);
            }
        }

        $mission = Mission::create($request->all());
        foreach($request->members as $index => $member){
            $mission->members()->attach($member, ['mission_role_id' => $request->roles[$index]]);
        }

        $mission->provinces()->attach($transportation['provinces']);
        $mission->operationalDistricts()->attach(array_filter($transportation['operational_districts']));
        $mission->healthFacilities()->attach(array_filter($transportation['health_facilities']));

        return redirect()->route('mission.index')->with('success',__('message.success_mission_saved'));

    }

    /**
     * Display the specified resource.
     * @param  int  $id
     */
    public function show($id)
    {
        $mission = Mission::with(
            'members',
            'objective',
            'healthFacilities',
            'operationalDistricts',
            'provinces'
        )->findOrFail($id);

        return view('missions.show', compact('mission'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     */
    public function edit($id)
    {
        $mission = Mission::with(
            'members',
            'healthFacilities',
            'operationalDistricts',
            'provinces'
        )->findOrFail($id);

        $employees = Employee::with(['position'],['department'])->get();
        $objectives = Objective::select('name','id')->get();
        $budgets = Budget::select('name','id')->get();
        $roles = MissionRole::select('name','id')->get();
        $transportations = Transportation::select('name','id','plate_number')->get();
        $provinces = Province::get();

        //dd($mission->reference_document);

        return view('missions.edit',[
            'mission' => $mission,
            'provinces' => $provinces,
            'employees'=>$employees,
            'roles' => $roles,
            'budgets'=>$budgets,
            'objectives'=>$objectives,
            'transportations'=>$transportations,
            'province_count' => $mission->provinces->count(),
            'od_count' => $mission->operationalDistricts->count() + $mission->provinces->count(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  MissionRequest  $request
     * @param  int  $id
     */
    public function update(MissionRequest $request, $id)
    {
        $requests = collect($request)->merge([
            'updated_by' => \Illuminate\Support\Facades\Auth::id(),
        ]);

        $transportation = $request->all();
        foreach($request->health_facilities as $index => $hf) {
            if ($request->health_facilities[$index] > 0){
               unset($transportation['operational_districts'][$index]);
               unset($transportation['provinces'][$index]);
            }
        }
        foreach($transportation['operational_districts'] as $index => $od) {
            if ($transportation['operational_districts'][$index] > 0){
                unset($transportation['provinces'][$index]);
            }
        }

        $mission =  Mission::find($id);
        $mission->update($requests->all());

        $mission->members()->detach();
        foreach($request->members as $index => $member){
            $mission->members()->attach($member, ['mission_role_id' => $request->roles[$index]]);
        }
        $mission->provinces()->sync($transportation['provinces']);
        $mission->operationalDistricts()->sync($transportation['operational_districts']);
        $mission->healthFacilities()->sync($transportation['health_facilities']);

        return redirect()->route('mission.index')->with('success',__('message.success_mission_updated'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     */
    public function destroy($id)
    {
        $delMission = Mission::find($id);
        $delMission->status_id = '0';
        $delMission->updated_by = Auth::user()->id;
        $delMission->save();
        return redirect()->route('mission.index')->with('success',__('message.success_mission_deleted'));

    }

    function getOdsByProId(Request $request){
        $proId = $request->proId;
        $ods = Province::find($proId)->operationalDistricts;
        return json_encode($ods);
    }

    function getFacByProId(Request $request){
        $OpsId = $request->OpsId;
        $hfs = OperationalDistrict::find($OpsId)->healthFacilities;
        return json_encode(collect($hfs));
    }

    function getPositionID(Request $request){

        $positionId = $request->positionId;
        $position = Employee::with(['position'],['department'])->find($positionId);
        return json_encode($position);
    }

    public function rebackDestroy($id)
    {
        $missionID = Mission::find($id);
        $missionID->status_id = '1';
        $missionID->updated_by = Auth::user()->id;
        $missionID->save();
        return back()->with('rebackSuccess','បេសកកម្មលេខ PCAMS'. $missionID->id .' ត្រូវបានត្រលប់វិញ');
    }

}

resources/views/missions/create.blade.php
<x-layout>
    <x-forms.base route="{{ route('mission.store') }}" enctype="multipart/form-data" backTo=" {{ route('mission.index') }}">
        <x-slot name="title">
            <h4>{{ __('mission.create') }}</h4>
        </x-slot>
        <div class="form-row mb-4">
            <div class="col-sm-3" >
                <x-forms.input name="code" label="{{ __('mission.code') }}"  ></x-forms.input>
            </div>
        </div>
        <x-forms.section>{{ __('app.general_information') }}</x-forms.section>
        <div class="form-row mb-4">
            <div class="col-sm-6">
                <x-forms.input name="reference_document" label="{{ __('mission.reference_document') }}" ></x-forms.input>
            </div>
            <div class="col-sm-3">
                <x-forms.date  name="leave_date" label="{{ __('mission.leave_date') }}"></x-forms.date>
            </div>
            <div class="col-sm-3">
                <x-forms.date name="return_date" label="{{ __('mission.return_date') }}"></x-forms.date>
            </div>
        </div>
        <div class="form-row mb-4">
            <div class="col">
                <x-forms.select name="objective_id" label="{{ __('mission.objective') }}" :collection="$objectives"></x-forms.select>
            </div>
            <div class="col">
                <livewire:transportation.select-box></livewire:transportation.select-box>
            </div>

            <div class="col">
                <x-forms.select name="budget_id" label="{{ __('mission.budget') }}" :collection="$budgets"></x-forms.select>
            </div>
        </div>
        <div class="form-row mb-4">
            <div class="col">
                <x-forms.textarea name="notes" label="{{ __('mission.note') }}"></x-forms.textarea>
            </div>

        </div>

        <x-forms.section>{{__('mission.destination')}}</x-forms.section>
        <div class="form-row mb-4">
            <x-forms.control-container class="col" name="provinces.*">
                <table class="table" id="tb-distination">
                    <thead>
                    <tr>
                        <x-tables.header>{{ __('#') }}</x-tables.header>
                        <x-tables.header class="w-25">{{ __('mission.province') }}</x-tables.header>
                        <x-tables.header class="w-25">{{ __('mission.operational_district') }}</x-tables.header>
                        <x-tables.header class="w-25">{{ __('mission.health_facility') }}</x-tables.header>
                        <x-tables.header><x-forms.button class="btn-sm add-destination-row"><i class="fas fa-plus-circle"></i></x-forms.button></x-tables.header>
                    </tr>
                    </thead>
                    <tbody>
                    <tr id="row_1">
                        <td class="destination-no" scope="row">1</td>
                        <td><x-forms.select name="provinces[]" class="data-provinces" :collection="$provinces" no-label label="{{ __('mission.province') }}"></x-forms.select></td>
                        <td><x-forms.select name="operational_districts[]" class="data-od" no-label id="od-1" label="{{ __('mission.operational_district') }}"></x-forms.select></td>
                        <td><x-forms.select name="health_facilities[]" class="data-hf" no-label id="fac-1" label="{{ __('mission.health_facility') }}"></x-forms.select></td>
                        <td><x-forms.button class="btn-sm remove btn-danger" data-id="'+trL+'"><i class="fas fa-minus-circle"></i></x-forms.button></td>
                    </tr>
                    </tbody>
                </table>
            </x-forms.control-container>
        </div><hr>

        <x-forms.section>{{ __('mission.member') }}</x-forms.section>


        <div class="form-row mb-4">
            <x-forms.control-container class="col" name="members.*">
            <table class="table" id="missionMember">
                    <thead>
                    <tr>
                        <x-tables.header>{{ __('#') }}</x-tables.header>
                        <x-tables.header class="w-75">{{ __('employee.name') }}</x-tables.header>
                        <x-tables.header hidden class="w-25">{{ __('mission.role') }}</x-tables.header>
                        <x-tables.header ><x-forms.button class="btn-sm addMissionMember"><i class="fas fa-plus-circle"></i></x-forms.button></x-tables.header>
                    </tr>
                    </thead>
                    <tbody>

                    <tr id="rowMember_1">
                        <td class="member-no" scope="row">1</td>
                        <td >
                            <x-forms.select name="members[]" class="select-member" :collection="$employees" no-label start="0" label="{{ __('mission.employee') }}"></x-forms.select>
                        </td>
                        <td hidden>
                            <x-forms.select  name="roles[]" class="form-control" :collection="$roles" no-label :selected="1" :value="1" label="{{ __('mission.role') }}"></x-forms.select>
                        </td>
                        <td>
                            <x-forms.button class="btn-sm removeMissionMember btn-danger" data-id="'+trL+'"><i class="fas fa-minus-circle"></i></x-forms.button>
                        </td>
                    </tr>

                    </tbody>
                </table>
            </x-forms.control-container>
        </div><hr>
    </x-forms.base>

    <x-slot name="header">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
        <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    </x-slot>

    <x-slot name="endbody">
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet" />
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
        @include('missions.script.form')
    </x-slot>

    @push('modal')
        <livewire:transportation.form></livewire:transportation.form>
    @endpush

    @include('utils.livewire')
</x-layout>

resources/views/missions/index.blade.php
<x-layout style="max-width: 100%">
    <x-layouts.card>
        <x-slot name="title">
            <div class="float-left">
                <h4>{{__('mission.index')}}</h4>
            </div>
            @can('mission-create')
                <div class="float-right">
                    <a href="{{ route('mission.create') }}" class="btn-primary btn ">បញ្ជូលបេសកម្មថ្មី</a>
                </div>
            @endcan
        </x-slot>

        <div class="col-12 py-2">
            <x-tables.base id="table_id">
                <x-slot name="header">
                    <x-tables.header>{{__('app.no')}}</x-tables.header>
                    <x-tables.header>{{__('mission.code')}}</x-tables.header>
                    <x-tables.header>{{__('mission.destination')}}</x-tables.header>
                    <x-tables.header>{{__('mission.member')}}</x-tables.header>
                    <x-tables.header>{{__('mission.leave_date')}}</x-tables.header>
                    <x-tables.header>{{__('mission.return_date')}}</x-tables.header>
{{--                    <x-tables.header>{{__('mission.objective')}}</x-tables.header>--}}
                    <x-tables.header>{{__('app.action')}}</x-tables.header>
                </x-slot>

                @php
                    $i=0;
                @endphp
                @foreach ($missions as $index => $mission)
                    <tr>
                        <td>{{ $index+1 }}</td>
                        <td>{{ Helper::knum($mission->code) }}</td>
                        <td style="width: 20%;font-size: 12px;">
                            @foreach ($mission->destinations as $destination)
                                <i class="fa fa-h-square" ></i>  {{ $destination }}<br/>
                            @endforeach
                        </td>
                        <td style="width: 25%;">
                            @foreach ($mission->members as  $member)
                            <b>{{ $member->fullname }}</b> {{$member->position->name}}<br/>
                            @endforeach
                        </td>
                        <td>{{ $mission->khLeaveDate }}</td>
                        <td>{{ $mission->khReturnDate }}</td>
{{--                        <td>{{ $mission->objective->name }}</td>--}}
                        <td>
                            <x-tables.action
                                id="{{ $index }}"
                                viewPermission="mission-detail"
                                editPermission="mission-edit"
                                deletePermission="mission-delete"
                                show="{{ route('mission.show', $mission->id) }}"
                                edit="{{ route('mission.edit', $mission->id) }}"
                                destroy="{{ route('mission.destroy', $mission->id) }}"></x-tables.action>
                        </td>
                    </tr>
                @endforeach

            </x-tables.base>
        </div>

    </x-layouts.card>

    <x-slot name="endbody">
        <script>
            $(document).ready( function () {
                $('#table_id').DataTable(
                    {
                        "language": {
                            url : "https://cdn.datatables.net/plug-ins/1.10.22/i18n/Khmer.json"
                        },
                    }
                );
            } );
        </script>

        <script>
            $('#reback').on("click",function() {
                var missionID = $(this).attr('value');
                $.ajax({
                    type: 'GET',
                    url: "{{ url('mission/reback') }}/"+missionID,
                    //data: { missionID: missionID },
                    dataType: 'JSON',
                    success: function (data) {
                        //  alert('lengDara');
                    },
                });
            });
        </script>
    </x-slot>

    <x-slot name="header">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
        <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js" defer></script>
        <link rel="stylesheet" href="//cdn.datatables.net/1.10.23/css/jquery.dataTables.min.css" />
    </x-slot>
</x-layout>

resources/views/missions/show.blade.php
<x-layout>
    <x-layouts.card>
        <x-slot name="title">
            <div class="row">
                <div class="col-4">
                    {{ __('app.mission') }} - {{ $mission->code }}
                </div>
                <div class="col-3">
                    {{ __('mission.leave_date') }} : {{ $mission->leave_date->diffForHumans() }}
                </div>
                <div class="col-3">
                    {{ __('mission.return_date') }} : {{ $mission->return_date->diffForHumans() }}
                </div>
                <div class="col-2">
                    <x-forms.button href="{{ route('mission.edit', $mission->id) }}">{{ __('app.edit') }}</x-forms.button>
                </div>
            </div>
{{--            @dump($mission->leave_date)--}}
        </x-slot>
        <div>

        </div>
    </x-layouts.card>
</x-layout>